# Generated by Django 4.1.1 on 2022-10-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('srname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('disability', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('county', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('dor', models.DateField()),
            ],
        ),
    ]
