# Generated by Django 4.1.1 on 2022-10-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeneficiaryDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Beneficiary',
        ),
    ]
