# Generated by Django 4.1.1 on 2022-10-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeneficiaryDB', '0002_rename_member_beneficiary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name_plural': 'Beneficiaries'},
        ),
    ]
